"use client";

import { CheckCircle2, Download } from "lucide-react";

export default function ReceiptPage() {
  const issuedAt = new Date().toLocaleString();

  return (
    <div style={{minHeight: "100svh", display: "grid", placeItems: "center", padding: 24}}>
      <div style={{width: "100%", maxWidth: 720, background: "#fff", color: "#0f1222", border: "1px solid #e9ebf4", borderRadius: 16, boxShadow: "0 12px 30px rgba(12,18,37,0.06)"}}>
        <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", padding: 16, borderBottom: "1px solid #eef1f7"}}>
          <div style={{display: "flex", alignItems: "center", gap: 8}}>
            <CheckCircle2 color="#16a34a" />
            <strong>Payment received</strong>
          </div>
          <button className="btn" onClick={() => window.print()} style={{border: "1px solid #e9ebf4"}}>
            <Download size={18} />
            Print / Save
          </button>
        </div>

        <div style={{display: "grid", gap: 12, padding: 16}}>
          <div style={{display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12}}>
            <div style={{border: "1px solid #e9ebf4", borderRadius: 12, padding: 12}}>
              <div style={{color: "#657090", fontSize: 12}}>Payer</div>
              <div style={{fontWeight: 700}}>Cloud Newton</div>
              <div style={{color: "#657090"}}>cloudnew@gmail.com</div>
            </div>
            <div style={{border: "1px solid #e9ebf4", borderRadius: 12, padding: 12}}>
              <div style={{color: "#657090", fontSize: 12}}>Receipt</div>
              <div style={{fontWeight: 700}}>RCT-42D42-0001</div>
              <div style={{color: "#657090"}}>Issued {issuedAt}</div>
            </div>
          </div>

          <div style={{border: "1px solid #e9ebf4", borderRadius: 12, overflow: "hidden"}}>
            <div style={{display: "grid", gridTemplateColumns: "2fr 1fr 1fr", padding: 12, background: "#f9faff", color: "#657090", fontSize: 12}}>
              <div>Description</div><div>Amount (KES)</div><div>Total (KES)</div>
            </div>
            <div style={{display: "grid", gridTemplateColumns: "2fr 1fr 1fr", padding: 12, borderTop: "1px solid #eef1f7"}}>
              <div>Invoice #42D42-0001</div><div>2,250.65</div><div>2,250.65</div>
            </div>
            <div style={{display: "grid", gridTemplateColumns: "2fr 1fr 1fr", padding: 12, borderTop: "1px solid #eef1f7"}}>
              <div>Platform fee (0.01%)</div><div>0.23</div><div>0.23</div>
            </div>
            <div style={{display: "grid", gridTemplateColumns: "2fr 1fr 1fr", padding: 12, borderTop: "1px solid #eef1f7", background: "#fbfcff"}}>
              <div style={{fontWeight: 700}}>Net settled</div><div></div><div style={{fontWeight: 800}}>2,250.42</div>
            </div>
          </div>

          <div style={{display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12}}>
            <div style={{border: "1px solid #e9ebf4", borderRadius: 12, padding: 12}}>
              <div style={{color: "#657090", fontSize: 12}}>Paid via</div>
              <div>Safaricom M-Pesa (C2B)</div>
              <div style={{color: "#657090"}}>Txn: RLQ9Y3Q2V • Phone: +254700000000</div>
            </div>
            <div style={{border: "1px solid #e9ebf4", borderRadius: 12, padding: 12}}>
              <div style={{color: "#657090", fontSize: 12}}>Settlement</div>
              <div>Instant settlement</div>
              <div style={{color: "#657090"}}>Paid out to your wallet</div>
            </div>
          </div>

          <div style={{textAlign: "center", color: "#657090", fontSize: 12}}>
            This receipt was generated by Paytrack. For support contact support@paytrack.dev
          </div>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          body { background: #fff !important; }
          .navbar, .footer, .ctaRow, .features, .codeBlock, .pricing { display: none !important; }
        }
        @media (max-width: 680px) {
          .receipt-grid-two { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}


