"""collection datas

Revision ID: 051ed0c9b978
Revises: 9336a89c5d74
Create Date: 2025-08-22 19:38:40.448961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051ed0c9b978'
down_revision = '9336a89c5d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.drop_column('mpesa_number')

    # ### end Alembic commands ###
