"""email-password to db

Revision ID: 08af029fa6f3
Revises: 101863c727b3
Create Date: 2025-10-15 15:02:57.472526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08af029fa6f3'
down_revision = '101863c727b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_tenants_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tenants_email'), type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
