"""payment_link-provider

Revision ID: 0bbc49eb08fe
Revises: 4a8b6c933a92
Create Date: 2025-08-22 18:57:19.683527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbc49eb08fe'
down_revision = '4a8b6c933a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('link_token', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payment_links_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_links'))
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_link_token'), ['link_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_links_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_payment_link_id_payment_links'), 'payment_links', ['payment_link_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_payment_link_id_payment_links'), type_='foreignkey')
        batch_op.drop_column('payment_link_id')

    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_links_updated_at'))
        batch_op.drop_index(batch_op.f('ix_payment_links_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_links_status'))
        batch_op.drop_index(batch_op.f('ix_payment_links_link_token'))
        batch_op.drop_index(batch_op.f('ix_payment_links_created_at'))

    op.drop_table('payment_links')
    # ### end Alembic commands ###
