"""update loggin to transactions

Revision ID: 101863c727b3
Revises: 2b85a2c4d2c3
Create Date: 2025-10-09 17:43:54.624829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101863c727b3'
down_revision = '2b85a2c4d2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recieving_mpesa_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recieving_b2b_account', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('recieving_b2b_account')
        batch_op.drop_column('recieving_mpesa_number')

    # ### end Alembic commands ###
