"""remove tracking_if

Revision ID: 123582f415ee
Revises: 051ed0c9b978
Create Date: 2025-08-22 21:01:31.687703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123582f415ee'
down_revision = '051ed0c9b978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.drop_constraint('uq_api_collections_tracking_id', type_='unique')
        batch_op.drop_column('tracking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('uq_api_collections_tracking_id', ['tracking_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
