"""change b2c to b2b

Revision ID: 2b85a2c4d2c3
Revises: d8a7eb5e06ce
Create Date: 2025-10-09 13:55:29.479638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b85a2c4d2c3'
down_revision = 'd8a7eb5e06ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b2b_account', sa.JSON(), nullable=True))
        batch_op.drop_column('b2c_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b2c_account', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('b2b_account')

    # ### end Alembic commands ###
