"""update the payment link

Revision ID: 3bc0f26b44be
Revises: 123582f415ee
Create Date: 2025-08-23 23:40:08.679105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc0f26b44be'
down_revision = '123582f415ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_api_collections_payment_link_id_payment_links'), 'payment_links', ['payment_link_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_collections_payment_link_id_payment_links'), type_='foreignkey')
        batch_op.drop_column('payment_link_id')

    # ### end Alembic commands ###
