"""addd_autopayout

Revision ID: 45db10d1f9fe
Revises: 7eb06b5452da
Create Date: 2025-10-16 16:26:43.943429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45db10d1f9fe'
down_revision = '7eb06b5452da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_payout', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_column('auto_payout')

    # ### end Alembic commands ###
