"""ledger update

Revision ID: 4a8b6c933a92
Revises: acd58a04544d
Create Date: 2025-08-22 17:47:39.111186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8b6c933a92'
down_revision = 'acd58a04544d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.create_index('idx_tenant_config', ['tenant_id'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('idx_tenant_created', ['tenant_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('idx_tenant_created')

    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_index('idx_tenant_config')

    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
