"""callback on tenant_co

Revision ID: 695ff34074ca
Revises: 71eab717ed95
Create Date: 2025-08-22 19:04:42.175984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695ff34074ca'
down_revision = '71eab717ed95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.alter_column('link_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.alter_column('link_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
