"""callback on tenant_config

Revision ID: 6b1c64d70eb8
Revises: 0bbc49eb08fe
Create Date: 2025-08-22 18:59:48.597145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1c64d70eb8'
down_revision = '0bbc49eb08fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_callback_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('link_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('api_callback_url')

    # ### end Alembic commands ###
