"""callback on tenant_confis

Revision ID: 71eab717ed95
Revises: 6b1c64d70eb8
Create Date: 2025-08-22 19:00:51.924937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71eab717ed95'
down_revision = '6b1c64d70eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_column('link_id')

    # ### end Alembic commands ###
