"""add payout default

Revision ID: 7eb06b5452da
Revises: 08af029fa6f3
Create Date: 2025-10-15 15:51:15.205625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb06b5452da'
down_revision = '08af029fa6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_config', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.drop_column('payout')

    # ### end Alembic commands ###
