"""collection data

Revision ID: 9336a89c5d74
Revises: 897a290f629e
Create Date: 2025-08-22 19:34:54.569378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9336a89c5d74'
down_revision = '897a290f629e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('request_reference', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('uq_api_collections_track_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_api_collections_tracking_id'), ['tracking_id'])
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_api_collections_tracking_id'), type_='unique')
        batch_op.create_unique_constraint('uq_api_collections_track_id', ['track_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('mpesa_checkout_request_id')
        batch_op.drop_column('request_reference')
        batch_op.drop_column('tracking_id')

    # ### end Alembic commands ###
