"""Add index on tenant_id in ApiKey

Revision ID: 9ca75ce28c11
Revises: baf167ddb314
Create Date: 2025-08-22 15:44:21.687658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca75ce28c11'
down_revision = 'baf167ddb314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_tenant_id')

    # ### end Alembic commands ###
