"""mnew postgress connection

Revision ID: baf167ddb314
Revises: 
Create Date: 2025-08-22 15:13:01.627826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf167ddb314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('api_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_keys_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_api_keys'))
    )
    op.create_table('tenant_config',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_config_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenant_config'))
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('account_no', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_transaction_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_table('ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_ledger_transaction_id_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    op.drop_table('transaction')
    op.drop_table('tenant_config')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
