"""add disbursmt

Revision ID: bb673eac2192
Revises: aae086f287b0
Create Date: 2025-08-26 13:29:57.442987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb673eac2192'
down_revision = 'aae086f287b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('request_reference', sa.String(length=255), nullable=False),
    sa.Column('mpesa_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('mpesa_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_disbursements_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_disbursements')),
    sa.UniqueConstraint('request_reference', name=op.f('uq_api_disbursements_request_reference'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_disbursements')
    # ### end Alembic commands ###
