"""add b2c_account to disbursement

Revision ID: d8a7eb5e06ce
Revises: fc66d7aef3b7
Create Date: 2025-10-09 13:36:54.836016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a7eb5e06ce'
down_revision = 'fc66d7aef3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b2c_account', sa.JSON(), nullable=True))
        batch_op.alter_column('mpesa_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_disbursements', schema=None) as batch_op:
        batch_op.alter_column('mpesa_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('b2c_account')

    # ### end Alembic commands ###
